#!/usr/bin/env bash
#
# This script will tally up all of your various fruits.
#
# It does not work or do anything interesting. Yet.
#
#
# https://www.youtube.com/watch?v=6Tou8-Cz8is

. ./functions.sh

CWD=`pwd`
BUILDENV="$CWD/tmp_img"
ROOTSIZE="80"
IMAGE="$BUILDENV/out.img"
ROOTFS="$BUILDENV/rootfs"

# check root is running
if [ $EUID -ne 0 ]; then
    error "you must run as root"
    exit 1
fi

# purge old build env
rm -rf $BUILDENV
mkdir -p $BUILDENV

# create blank image $ROOTSIZE blocks long
info "creating blank image $IMAGE"
dd if=/dev/zero of=$IMAGE bs=1MiB count=$ROOTSIZE >& /dev/null

# create partition table
# (sunxi needs first 2kb free for bootloader to be installed)
# from 2048 to full card ext4
info "creating filesystems"
fdisk $IMAGE >& /dev/null << EOF
n
p
1
2048

w
EOF

# create device map
info "creating loop device"
DEVICE=`kpartx -a -v $IMAGE | sed -E 's/.*(loop[0-9])p.*/\1/g' | head -1`
sleep 1
DEVICE_ROOTFS="/dev/mapper/${DEVICE}p1"
info "created loop device $DEVICE"

# format
info "formatting rootfs"
mkfs.ext4 $DEVICE_ROOTFS >& /dev/null

# mount
info "mounting rootfs"
mkdir -p $ROOTFS
mount $DEVICE_ROOTFS $ROOTFS

# do evil things to the rootfs here

# loop over all of the scripts
for SHELL_SCRIPT in scripts/*.sh; do
    info "Running $SHELL_SCRIPT"
    . "$SHELL_SCRIPT"
done

# stop the doing evil things to the rootfs here

# unmount
info "unmounting rootfs"
cd $CWD
umount $DEVICE_ROOTFS

# remove the device maps
info "removing loop devices"
kpartx -d $DEVICE_ROOTFS > /dev/null

sleep 2

# install bootloader
info "installing bootloader from $KERNEL_TMP"
dd conv=notrunc if=$KERNEL_TMP/u-boot/u-boot-sunxi-with-spl.bin of=$IMAGE bs=8k seek=1

# exit
info "completed!"
exit 0