#!/usr/bin/env bash
#
# This script will tally up all of your various fruits.
#
# It does not work or do anything interesting. Yet.
#
#
# https://www.youtube.com/watch?v=6Tou8-Cz8is



CWD=`pwd`
BUILDENV="$CWD/tmp"
ROOTSIZE="1500"
IMAGE="$BUILDENV/out.img"
ROOTFS="$BUILDENV/rootfs"

# check root is running
if [ $EUID -ne 0 ]; then
    echo "you must run as root"
    exit 1
fi

# purge old build env
rm -rf $BUILDENV
mkdir -p $BUILDENV

# create blank image $ROOTSIZE blocks long
echo "TALLYMAN: creating blank image $IMAGE"
dd if=/dev/zero of=$IMAGE bs=1MiB count=$ROOTSIZE >& /dev/null

# create partition table
# (sunxi needs first 2kb free for bootloader to be installed)
# from 2048 to full card ext4
echo "TALLYMAN: creating filesystems"
fdisk $IMAGE >& /dev/null << EOF
n
p
1
2048

w
EOF

# create device map
echo "TALLYMAN: creating loop device"
DEVICE=`kpartx -a -v $IMAGE | sed -E 's/.*(loop[0-9])p.*/\1/g' | head -1`
sleep 1
DEVICE_ROOTFS="/dev/mapper/${DEVICE}p1"
echo "TALLYMAN: created loop device $DEVICE"

# format
echo "TALLYMAN: formatting rootfs"
mkfs.ext4 $DEVICE_ROOTFS >& /dev/null

# mount
echo "TALLYMAN: mounting rootfs"
mkdir -p $ROOTFS
mount $DEVICE_ROOTFS $ROOTFS

# do evil things to the rootfs here

# loop over all of the scripts
for SHELL_SCRIPT in scripts/*.sh; do
    echo "Running $SHELL_SCRIPT"
    . "$SHELL_SCRIPT"
done

# stop the doing evil things to the rootfs here

# unmount
echo "TALLYMAN: unmounting rootfs"
cd $CWD
umount $DEVICE_ROOTFS

# remove the device maps
echo "TALLYMAN: removing loop devices"
kpartx -d $DEVICE_ROOTFS > /dev/null

# exit
echo "TALLYMAN: completed!"
exit 0